# Generated by Django 3.2.8 on 2021-11-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso_bd',
            name='pregunta',
            field=models.TextField(),
        ),
    ]
