# Generated by Django 3.2.8 on 2021-11-27 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=500)),
                ('contenido', models.TextField()),
                ('fecha', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
